(function attachBirthBenefits(root) {
  const data = {
    meta: {
      verifiedAt: "2026-08-20",
      audience: "첫째·단태아·천안시 출생등록 예정 가정",
      summaryBasis: "임신부터 출생 후 24개월 기준",
      notice:
        "지원 제도와 예산은 바뀔 수 있습니다. 신청 전 공식 페이지와 주소지 행정복지센터에서 최신 조건을 다시 확인하세요.",
    },
    categories: [
      { id: "pregnancy", title: "임신 중 미리 신청", description: "출산 전에 신청하거나 임신 중 이용할 수 있는 의료·보건·생활 지원" },
      { id: "birth-registration", title: "출생신고와 함께", description: "출생신고 때 행복출산 원스톱서비스와 함께 신청하면 편한 항목" },
      { id: "separate", title: "별도 신청", description: "보건소·한전 등에 신청하거나 별도 예약해야 하는 항목" },
      { id: "health", title: "의료·건강 지원", description: "출생 직후부터 월령에 맞춰 챙겨야 하는 검사와 건강관리" },
      { id: "childcare", title: "영아기 돌봄", description: "생후 3~6개월부터 이용할 수 있는 긴급·틈새 돌봄 서비스" },
      { id: "conditional", title: "조건부 혜택", description: "가구 상황이나 출생 조건을 확인한 뒤 신청하는 항목" },
    ],
    items: [
      {
        id: "pregnancy-medical-voucher",
        category: "pregnancy",
        scope: "national",
        title: "건강보험 임신·출산 진료비",
        amount: "단태아 임신 1회당 100만 원 · 국민행복카드",
        summaryAmount: 1000000,
        eligibility: "임신확인서로 임신이 확인된 건강보험 가입자 또는 피부양자",
        timingLabel: "임신 확인 후 신청 · 출산일 이후 2년까지 산모와 2세 미만 영유아 진료에 사용",
        timing: { startDays: -280, endDays: 730, warningDays: 60 },
        office: "국민건강보험공단·카드사·정부24 맘편한 임신",
        preparation: "의료기관이 등록한 임신확인정보 또는 임신확인서",
        sourceTitle: "국민건강보험 임신·출산 진료비 지급 기준",
        sourceUrl: "https://www.nhis.or.kr/lm/lmxsrv/law/lawFullContent.do?MODE=threeView&SEQ=86&SEQ_HISTORY=613523",
        conditional: false,
      },
      {
        id: "cheonan-prenatal-screening",
        category: "pregnancy",
        scope: "local",
        title: "천안시 산전 초기검사",
        amount: "빈혈·간기능·혈액형·매독·에이즈·B형간염·소변검사 지원",
        summaryAmount: null,
        eligibility: "보건소에 등록한 임신 6~10주 초기 임신부",
        timingLabel: "임신 6~10주에 주소지 관할 보건소 방문",
        timing: { startDays: -238, endDays: -210, warningDays: 7 },
        office: "천안시 동남구·서북구 보건소",
        preparation: "신분증, 임신확인증 또는 산모수첩",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: false,
      },
      {
        id: "folic-acid-iron",
        category: "pregnancy",
        scope: "local",
        title: "임산부 엽산제·철분제",
        amount: "엽산제와 철분제 최대 5개월분 · 임신 주수별 차등",
        summaryAmount: null,
        eligibility: "천안시 보건소 등록 임산부",
        timingLabel: "엽산제 임신 12주까지, 철분제 임신 16주 이후",
        timing: { startDays: -280, endDays: 0, warningDays: 30 },
        office: "주소지 관할 보건소·정부24 맘편한 임신",
        preparation: "산모수첩 또는 임신확인서, 신분증",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: false,
      },
      {
        id: "high-risk-pregnancy-care",
        category: "pregnancy",
        scope: "conditional",
        title: "고위험 임산부 의료비",
        amount: "입원치료 관련 본인부담·비급여의 90% · 최대 300만 원",
        summaryAmount: null,
        eligibility: "19대 고위험 임신질환으로 진단받고 입원치료한 임산부 · 소득기준 없음",
        timingLabel: "퇴원 후 보건소 또는 e보건소에서 신청기한 확인",
        timing: null,
        office: "주소지 관할 보건소·e보건소·아이마중 앱",
        preparation: "진단서, 입퇴원확인서, 진료비 영수증·세부내역서, 통장 사본",
        sourceTitle: "보건복지부 고위험 임산부 의료비 지원",
        sourceUrl: "https://www.mohw.go.kr/menu.es?mid=a10711020200",
        conditional: true,
      },
      {
        id: "cesarean-copay",
        category: "pregnancy",
        scope: "conditional",
        title: "제왕절개 분만 본인부담 경감",
        amount: "건강보험 적용 제왕절개 분만 본인부담률 0%",
        summaryAmount: null,
        eligibility: "제왕절개로 분만하는 산모 · 비급여와 선별급여는 제외",
        timingLabel: "분만 의료기관에서 건강보험 적용 범위 확인",
        timing: null,
        office: "분만 의료기관·국민건강보험공단",
        preparation: "별도 신청 여부와 비급여 항목을 의료기관에 확인",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: true,
      },
      {
        id: "pregnant-parking-discount",
        category: "pregnancy",
        scope: "local",
        title: "천안시 임산부 공영주차장 면제",
        amount: "천안시 관내 공영주차장 주차요금 100% 감면",
        summaryAmount: null,
        eligibility: "천안시에 주민등록을 둔 임신부 또는 분만 후 6개월 미만 여성",
        timingLabel: "임신 중부터 분만 후 6개월 미만까지",
        timing: { startDays: -280, endDays: 183, warningDays: 30 },
        office: "주소지 관할 보건소에서 임산부 자동차 표지 발급",
        preparation: "신분증, 임신확인자료, 차량 정보",
        sourceTitle: "천안시 출산장려 및 다자녀가정 우대정책",
        sourceUrl: "https://www.cheonan.go.kr/images/life/sub14/sub14_03_file.pdf",
        conditional: false,
      },
      {
        id: "pregnancy-parenting-class",
        category: "pregnancy",
        scope: "local",
        title: "건강한 임신·출산·육아 교실",
        amount: "모유수유·출산호흡·신생아 돌봄·산후우울 예방 교육",
        summaryAmount: null,
        eligibility: "천안시 임산부·출산부",
        timingLabel: "보건소별 교육 일정과 모집기간 확인",
        timing: { startDays: -280, endDays: 183, warningDays: 0 },
        office: "천안시 동남구·서북구 보건소",
        preparation: "신청 일정과 온라인·방문 수강 방식을 사전 확인",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: false,
      },
      {
        id: "first-meeting-voucher",
        category: "birth-registration",
        scope: "national",
        title: "첫만남이용권",
        amount: "첫째 200만 원 국민행복카드 포인트",
        summaryAmount: 2000000,
        eligibility: "출생신고되어 주민등록번호를 부여받은 첫째 아동",
        timingLabel: "출생 후 신청, 사용기한은 아동 출생일로부터 1년",
        timing: { startDays: 0, endDays: 365, warningDays: 30 },
        office: "주소지 행정복지센터·복지로·정부24 행복출산",
        preparation: "보호자 신분증, 국민행복카드 또는 카드 발급 준비",
        sourceTitle: "보건복지부 임신·출산·양육 지원 확대 안내",
        sourceUrl: "https://www.mohw.go.kr/board.es?act=view&bid=0027&list_no=1479667&mid=a10503000000",
        conditional: false,
      },
      {
        id: "parent-benefit",
        category: "birth-registration",
        scope: "national",
        title: "부모급여",
        amount: "0세 월 100만 원, 1세 월 50만 원 · 24개월 최대 1,800만 원",
        summaryAmount: 18000000,
        eligibility: "0~23개월 아동, 소득과 무관 · 어린이집 이용 시 보육료와 정산",
        timingLabel: "출생 후 60일 이내 신청하면 출생월부터 소급",
        timing: { startDays: 0, endDays: 60, warningDays: 14 },
        office: "주소지 행정복지센터·복지로·정부24 행복출산",
        preparation: "보호자 신분증, 지급계좌 정보",
        sourceTitle: "보건복지부 부모급여 안내",
        sourceUrl: "https://www.mohw.go.kr/board.es?act=view&bid=0027&list_no=1479667&mid=a10503000000",
        conditional: false,
      },
      {
        id: "child-allowance",
        category: "birth-registration",
        scope: "national",
        title: "아동수당",
        amount: "2026년 천안 기준 월 10만 5천 원 · 첫 24개월 252만 원",
        summaryAmount: 2520000,
        eligibility: "2026년 9세 미만 아동 · 비수도권 월 5천 원 추가",
        timingLabel: "출생 후 60일 이내 신청하면 출생월부터 소급",
        timing: { startDays: 0, endDays: 60, warningDays: 14 },
        office: "주소지 행정복지센터·복지로·정부24 행복출산",
        preparation: "보호자 신분증, 지급계좌 정보",
        sourceTitle: "보건복지부 2026년 아동수당 확대 안내",
        sourceUrl: "https://www.mohw.go.kr/gallery.es?act=view&b_list=12&bid=0003&cg_code=C02&keyField=&list_no=380007&mid=a10606030000&nPage=1&orderby=&vlist_no_npage=3",
        conditional: false,
      },
      {
        id: "cheonan-birth-grant",
        category: "birth-registration",
        scope: "local",
        title: "천안시 출생축하금",
        amount: "첫째 30만 원",
        summaryAmount: 300000,
        eligibility: "영아 출생월 6개월 전부터 신청일까지 천안시에 계속 주민등록을 둔 가정",
        timingLabel: "출생신고 후 주소지 행정복지센터에서 신청",
        timing: { startDays: 0, endDays: null, warningDays: 0 },
        office: "주소지 행정복지센터·복지로",
        preparation: "거주기간 확인, 보호자 신분증, 지급계좌 정보",
        sourceTitle: "천안시 출산장려 및 다자녀가정 우대정책",
        sourceUrl: "https://www.cheonan.go.kr/images/life/sub14/sub14_03_file.pdf",
        conditional: false,
      },
      {
        id: "cheonan-postpartum-care",
        category: "birth-registration",
        scope: "local",
        title: "천안형 산후조리 지원",
        amount: "일반 단태아 50만 원 · 천안사랑카드",
        summaryAmount: 500000,
        eligibility: "출생일 6개월 전부터 천안시에 주민등록을 둔 부 또는 모, 천안시 출생등록",
        timingLabel: "아기 출생일 이후 6개월 이내",
        timing: { startDays: 0, endDays: 183, warningDays: 30 },
        office: "주소지 관할 보건소",
        preparation: "주민등록·출생등록 확인, 천안사랑카드",
        sourceTitle: "천안시 2025 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: false,
      },
      {
        id: "chungnam-car-seat",
        category: "birth-registration",
        scope: "local",
        title: "충남 영유아 교통안전용품",
        amount: "2026년 지원 카시트 6종 중 1개 선택",
        summaryAmount: null,
        eligibility: "2026년 충남 출생등록 신생아, 부모 중 1명이 출생등록일 기준 충남에 12개월 이상 주민등록",
        timingLabel: "출생신고 시 행정복지센터에서 함께 신청",
        timing: { startDays: 0, endDays: null, warningDays: 0 },
        office: "읍·면·동 행정복지센터",
        preparation: "부모 거주기간 확인, 희망 제품과 배송지 결정",
        sourceTitle: "충청남도 2026 영유아 교통안전용품 지원사업",
        sourceUrl: "https://www.chungnam.go.kr/cnportal/media/article/view.do?articleNo=MD0003296445&articleSectNo2=500170&menuNo=500170",
        conditional: false,
      },
      {
        id: "cheonan-birth-gift",
        category: "birth-registration",
        scope: "local",
        title: "천안시 신생아 출생축하용품",
        amount: "출생축하용품 지급 · 실제 품목은 신청 시 확인",
        summaryAmount: null,
        eligibility: "천안시에 주민등록을 두고 천안시에 출생신고한 가정",
        timingLabel: "출생신고 시 주소지 행정복지센터에서 신청",
        timing: { startDays: 0, endDays: null, warningDays: 0 },
        office: "주소지 행정복지센터",
        preparation: "보호자 신분증, 출생등록 확인",
        sourceTitle: "천안시 출산장려 및 다자녀가정 우대정책",
        sourceUrl: "https://www.cheonan.go.kr/images/life/sub14/sub14_03_file.pdf",
        conditional: false,
      },
      {
        id: "electricity-discount",
        category: "separate",
        scope: "national",
        title: "출산가구 전기요금 할인",
        amount: "주택용 전기요금 30% · 월 최대 1만 6천 원",
        summaryAmount: null,
        eligibility: "주민등록표상 출생일로부터 3년 미만 영아가 포함된 주거용 가구",
        timingLabel: "출생신고 후 신청 · 신청월분부터 적용 여부 확인",
        timing: { startDays: 0, endDays: null, warningDays: 0 },
        office: "한국전력 123·한전ON·행복출산 원스톱서비스",
        preparation: "전기요금 고객번호, 주소와 세대 정보",
        sourceTitle: "한국전력 전기요금 복지할인 안내",
        sourceUrl: "https://home.kepco.co.kr/kepco/front/html/WZ/2018_11_12/sub15.html",
        conditional: false,
      },
      {
        id: "postpartum-helper",
        category: "separate",
        scope: "conditional",
        title: "산모·신생아 건강관리",
        amount: "산후관리사 이용 바우처 · 소득구간과 이용기간에 따라 차등",
        summaryAmount: null,
        eligibility: "기준중위소득 150% 이하 또는 천안시 예외지원 조건 충족 가정",
        timingLabel: "출산예정일 40일 전부터 출산 후 60일까지",
        timing: { startDays: -40, endDays: 60, warningDays: 14 },
        office: "산모 주민등록지 관할 보건소·복지로",
        preparation: "건강보험료 확인자료, 가족관계·재직·휴직 관련 서류(해당 시)",
        sourceTitle: "천안시 산모·신생아 건강관리 지원사업",
        sourceUrl: "https://mng.cheonan.go.kr/dhealth/sub03_04_03.do",
        conditional: true,
      },
      {
        id: "postpartum-helper-copay-refund",
        category: "separate",
        scope: "conditional",
        title: "산모·신생아 건강관리 본인부담금 환급",
        amount: "서비스 본인부담금의 90% · 최대 40만 원",
        summaryAmount: null,
        eligibility: "정부지원 산모·신생아 건강관리 이용 가정 중 출산일 기준 충남 6개월 이상 거주, 중위소득 150% 이하",
        timingLabel: "서비스 이용 종료 다음 날부터 6개월 이내",
        timing: null,
        office: "산모 주민등록지 관할 보건소",
        preparation: "서비스 이용·본인부담금 납부 증빙, 주민등록·소득 확인자료",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: true,
      },
      {
        id: "breast-pump-rental",
        category: "separate",
        scope: "local",
        title: "전동 유축기 무료 대여",
        amount: "전동 유축기 본체 1개월 대여",
        summaryAmount: null,
        eligibility: "부 또는 모가 천안시에 주민등록을 둔 출산가정 · 재고 확인 필요",
        timingLabel: "출산 후 보건소에 대여 가능 시기와 재고 확인",
        timing: { startDays: 0, endDays: null, warningDays: 0 },
        office: "천안시 동남구·서북구 보건소",
        preparation: "보호자 신분증, 출생 및 주소 확인자료",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: false,
      },
      {
        id: "newborn-screening",
        category: "health",
        scope: "conditional",
        title: "신생아 선별·확진검사 지원",
        amount: "선천성대사이상·난청 검사비 등 항목별 지원",
        summaryAmount: null,
        eligibility: "검사 종류, 외래검사 여부와 확진 결과에 따라 지원 범위가 다름",
        timingLabel: "일부 선별검사는 출생 후 28일 이내 · 병원과 보건소에 확인",
        timing: { startDays: 0, endDays: 28, warningDays: 7 },
        office: "분만 의료기관·주소지 관할 보건소",
        preparation: "진료비 영수증, 검사결과지, 진료비 상세내역서(해당 시)",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: true,
      },
      {
        id: "metabolic-special-diet",
        category: "health",
        scope: "conditional",
        title: "선천성대사이상아 의료비·특수식이",
        amount: "질환별 의료비, 특수조제분유와 저단백 식품 지원",
        summaryAmount: null,
        eligibility: "정밀검사에서 선천성대사이상 또는 희귀난치성질환으로 진단된 만 19세 미만 아동",
        timingLabel: "확진 후 가능한 빨리 관할 보건소에 지원 품목과 절차 확인",
        timing: null,
        office: "주소지 관할 보건소·e보건소·아이마중 앱",
        preparation: "진단서, 검사결과지, 지원 품목별 구비서류",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: true,
      },
      {
        id: "atopy-asthma-care",
        category: "health",
        scope: "conditional",
        title: "아토피·천식 의료비",
        amount: "관련 진료비·약제비 본인부담금 연 최대 20만 원",
        summaryAmount: null,
        eligibility: "만 18세 이하 아토피·천식 환자 중 의료급여 또는 기준중위소득 120% 이하",
        timingLabel: "진단·치료 후 당해연도 예산 소진 전 보건소 문의",
        timing: null,
        office: "주소지 관할 보건소",
        preparation: "진단자료, 진료비 영수증, 건강보험료·소득 확인자료",
        sourceTitle: "천안시 아토피·천식 의료비 지원",
        sourceUrl: "https://mng.cheonan.go.kr/dhealth/sub04_15.do",
        conditional: true,
      },
      {
        id: "national-vaccination",
        category: "health",
        scope: "national",
        title: "어린이 국가예방접종",
        amount: "국가예방접종 지원사업 대상 백신 접종비 지원",
        summaryAmount: null,
        eligibility: "예방접종 지원 대상 연령의 어린이",
        timingLabel: "출생 직후 B형간염부터 표준 일정에 맞춰 접종",
        timing: { startDays: 0, endDays: null, warningDays: 0 },
        office: "보건소·예방접종 지정 의료기관",
        preparation: "아기수첩, 보호자 신분증, 예방접종 기록",
        sourceTitle: "질병관리청 예방접종도우미",
        sourceUrl: "https://nip.kdca.go.kr/irhp/index.jsp",
        conditional: false,
      },
      {
        id: "infant-health-checkup",
        category: "health",
        scope: "national",
        title: "영유아 건강검진",
        amount: "생후 14일부터 71개월까지 시기별 건강·구강검진",
        summaryAmount: null,
        eligibility: "건강보험 영유아 건강검진 대상 아동",
        timingLabel: "1차 검진은 생후 14~35일 · 이후 월령별 기간 확인",
        timing: { startDays: 14, endDays: 35, warningDays: 7 },
        office: "국민건강보험공단 지정 영유아 검진기관",
        preparation: "문진표, 보호자 신분증, 아기수첩",
        sourceTitle: "국민건강보험공단 영유아 건강검진 안내",
        sourceUrl: "https://www.nhis.or.kr/nhis/healthin/wbhaca04800m01.do",
        conditional: false,
      },
      {
        id: "chungnam-365-childcare",
        category: "childcare",
        scope: "local",
        title: "힘쎈충남 365×24 어린이집",
        amount: "야간·새벽·주말·공휴일 돌봄 · 부모부담 시간당 2천 원",
        summaryAmount: null,
        eligibility: "생후 6개월 이상 7세 이하 미취학 영유아",
        timingLabel: "생후 6개월부터 사전예약 · 긴급한 경우 당일예약 가능 여부 확인",
        timing: { startDays: 183, endDays: 2555, warningDays: 0 },
        office: "충남육아종합지원센터 아이키움뜰·천안 지정 어린이집",
        preparation: "이용 아동 등록, 이용시간과 천안 제공기관 예약 가능 여부 확인",
        sourceTitle: "충남 365×24 어린이집 안내",
        sourceUrl: "https://youth.chungnam.go.kr/web/main/bbs/cnyouth_notice/204",
        conditional: false,
      },
      {
        id: "childcare-service",
        category: "childcare",
        scope: "conditional",
        title: "아이돌봄서비스",
        amount: "시간제·영아종일제 돌봄 · 소득유형별 정부지원 차등",
        summaryAmount: null,
        eligibility: "생후 3개월~12세 이하 아동 중 맞벌이 등 양육공백 가정",
        timingLabel: "생후 3개월 전 소득판정과 서비스 회원가입을 미리 준비",
        timing: { startDays: 90, endDays: 4380, warningDays: 0 },
        office: "천안시건강가정지원센터·아이돌봄서비스",
        preparation: "정부지원 자격판정, 국민행복카드, 서비스 이용자 등록",
        sourceTitle: "천안시 아이돌봄지원사업",
        sourceUrl: "https://gongyoo.cheonan.go.kr/kor/sub06_04_20.do",
        conditional: true,
      },
      {
        id: "out-of-hospital-birth",
        category: "conditional",
        scope: "conditional",
        title: "의료기관 외 출산비",
        amount: "자녀 수와 관계없이 출산 1회당 25만 원",
        summaryAmount: null,
        eligibility: "병원·의원·조산원이 아닌 자택 등에서 출산한 건강보험 가입자·피부양자 또는 의료급여 수급자",
        timingLabel: "출산 후 국민건강보험공단 또는 행정복지센터에 신청",
        timing: null,
        office: "국민건강보험공단·주소지 행정복지센터",
        preparation: "출산 사실과 출생아 관계를 확인할 수 있는 서류",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: true,
      },
      {
        id: "disabled-woman-birth-grant",
        category: "conditional",
        scope: "conditional",
        title: "천안시 여성장애인 출산지원금",
        amount: "장애 정도에 따라 신생아 1명당 120만~150만 원",
        summaryAmount: null,
        eligibility: "출생일 6개월 전부터 신청일까지 천안시에 계속 거주한 여성장애인 · 4개월 이상 유산·사산 포함",
        timingLabel: "출산 후 주소지 행정복지센터에 신청",
        timing: null,
        office: "주소지 행정복지센터",
        preparation: "장애인 등록, 거주기간, 출산·유산·사산 확인서류",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: true,
      },
      {
        id: "teen-mother-medical",
        category: "conditional",
        scope: "conditional",
        title: "청소년 산모 임신·출산 의료비",
        amount: "임신 1회당 최대 120만 원 · 국민행복카드",
        summaryAmount: null,
        eligibility: "임신확인일 기준 만 19세 이하 산모",
        timingLabel: "임신 중 또는 출산 후 신청 · 출산일 이후 2년까지 사용",
        timing: null,
        office: "사회서비스 전자바우처·한국사회보장정보원",
        preparation: "임신확인서, 연령과 본인 확인자료, 국민행복카드",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: true,
      },
      {
        id: "diaper-formula-voucher",
        category: "conditional",
        scope: "conditional",
        title: "저소득층 기저귀·조제분유",
        amount: "기저귀 월 9만 원, 조제분유 추가 월 11만 원 · 최대 24개월",
        summaryAmount: null,
        eligibility: "기초생활·차상위·한부모 또는 소득요건을 충족한 장애인·다자녀 가구, 조제분유는 별도 사유 필요",
        timingLabel: "출생 후 60일 이내 신청하면 24개월 전체 지원",
        timing: null,
        office: "주소지 보건소·행정복지센터·복지로",
        preparation: "사회보장급여 신청서, 소득·가구유형 및 조제분유 사유 증빙",
        sourceTitle: "보건복지부 저소득층 기저귀·조제분유 지원",
        sourceUrl: "https://www.mohw.go.kr/menu.es?mid=a10711020100",
        conditional: true,
      },
      {
        id: "nutrition-plus",
        category: "conditional",
        scope: "conditional",
        title: "영양플러스 보충영양",
        amount: "월 1회 이상 영양교육과 대상별 보충식품 기본 6개월",
        summaryAmount: null,
        eligibility: "기준중위소득 65% 이하이며 빈혈 등 영양위험요인이 있는 임산부·수유부·66개월 미만 영유아",
        timingLabel: "보건소에 대기 여부와 자격판정 일정을 먼저 확인",
        timing: null,
        office: "주소지 관할 보건소",
        preparation: "소득 확인자료와 영양위험 평가",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: true,
      },
      {
        id: "postpartum-care-tax-credit",
        category: "conditional",
        scope: "conditional",
        title: "산후조리비 의료비 세액공제",
        amount: "산후조리원 비용 연 200만 원 한도로 의료비 세액공제 대상",
        summaryAmount: null,
        eligibility: "산후조리원 비용을 지출한 근로소득자 등 · 2024년부터 소득기준 폐지",
        timingLabel: "결제 영수증을 보관해 해당 연도 연말정산·종합소득세 신고에 반영",
        timing: null,
        office: "회사 연말정산·국세청 홈택스",
        preparation: "산후조리원 영수증과 의료비 자료 반영 여부 확인",
        sourceTitle: "보건복지부 2024 임신·출산·양육 지원 확대",
        sourceUrl: "https://www.mohw.go.kr/board.es?act=view&bid=0027&list_no=1479667&mid=a10503000000",
        conditional: true,
      },
      {
        id: "birth-gift-tax-deduction",
        category: "conditional",
        scope: "conditional",
        title: "혼인·출산 증여재산 공제",
        amount: "출생일 전후 2년 내 직계존속 증여재산 최대 1억 원 추가 공제",
        summaryAmount: null,
        eligibility: "출산일 전후 2년 안에 부모 등 직계존속으로부터 재산을 증여받는 경우",
        timingLabel: "증여 전 공제 한도와 신고기한을 세무 전문가·국세청에 확인",
        timing: null,
        office: "국세청 홈택스·세무서",
        preparation: "증여일·증여자·기존 증여 내역과 출생일 확인자료",
        sourceTitle: "보건복지부 2024 임신·출산·양육 지원 확대",
        sourceUrl: "https://www.mohw.go.kr/board.es?act=view&bid=0027&list_no=1479667&mid=a10503000000",
        conditional: true,
      },
      {
        id: "father-leave-grant",
        category: "conditional",
        scope: "conditional",
        title: "천안시 아빠육아휴직 장려금",
        amount: "월 30만 원 · 최대 6개월, 최대 180만 원",
        summaryAmount: 1800000,
        eligibility: "신청일 기준 천안시 1년 이상 거주 남성 육아휴직자, 자녀도 천안 거주, 고용보험 급여요건 충족",
        timingLabel: "육아휴직급여 지급요건 충족 후 주소지 행정복지센터 확인",
        timing: null,
        office: "주소지 행정복지센터",
        preparation: "육아휴직급여 지급결정 자료, 주민등록·재직 관련 서류",
        sourceTitle: "천안시 출산장려 및 다자녀가정 우대정책",
        sourceUrl: "https://www.cheonan.go.kr/images/life/sub14/sub14_03_file.pdf",
        conditional: true,
      },
      {
        id: "premature-congenital-care",
        category: "conditional",
        scope: "conditional",
        title: "미숙아·선천성이상아 의료비 지원",
        amount: "출생체중·진단·의료비에 따라 차등 지원",
        summaryAmount: null,
        eligibility: "미숙아 또는 출생 후 일정 기간 내 선천성이상 진단·입원수술 등 세부 요건 충족",
        timingLabel: "퇴원 후 가능한 빨리 관할 보건소에 신청기한 확인",
        timing: null,
        office: "주소지 관할 보건소",
        preparation: "진단서, 입퇴원확인서, 진료비 영수증·상세내역서",
        sourceTitle: "천안시 임신·출산·육아 가이드",
        sourceUrl: "https://mng.cheonan.go.kr/images/life/sub14/baby_guide01_2025.pdf",
        conditional: true,
      },
      {
        id: "second-child-benefits",
        category: "conditional",
        scope: "conditional",
        title: "둘째 이상·다자녀 추가 혜택",
        amount: "종량제봉투 20L 100매, 행복키움카드와 시설·요금 감면 등",
        summaryAmount: null,
        eligibility: "둘째 이상 또는 제도별 다자녀 기준 충족 가정 · 현재 첫째 기준에서는 비대상",
        timingLabel: "둘째 이상 출생신고 시 제도별 자녀 수 기준 확인",
        timing: null,
        office: "주소지 행정복지센터·NH농협은행·각 시설",
        preparation: "주민등록등본 또는 가족관계증명서",
        sourceTitle: "천안시 출산장려 및 다자녀가정 우대정책",
        sourceUrl: "https://www.cheonan.go.kr/images/life/sub14/sub14_03_file.pdf",
        conditional: true,
      },
    ],
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = data;
  }

  if (root) {
    root.BIRTH_BENEFITS_DATA = data;
  }
})(typeof window !== "undefined" ? window : globalThis);
